name: Generate Homebrew Formula

on:
  push:
    branches: [main]

jobs:
  generate-formula:
    runs-on: ubuntu-latest
    name: Generate Formula from YAML

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Generate Formula
        run: |
          cd scripts
          go run generate_formula.go

      - name: Check if formula changed
        run: |
          git config --global user.name "kiosk bot"
          git config --global user.email "actions@github.com"
          git add Formula/
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Update generated Homebrew formula"
            git push origin main
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}