name: Generate Homebrew Formula

on:
  push:
    branches: [main]

jobs:
  generate-formula:
    runs-on: ubuntu-latest
    name: Generate Formula from YAML

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.BREWRELEASE }}

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Generate Formula
        run: go run scripts/generate_formula.go